namespace SpriteKind {
    export const Helicopter = SpriteKind.create()
    export const Cloud = SpriteKind.create()
    export const LandingPad = SpriteKind.create()
    export const mounatin = SpriteKind.create()
    export const mountain = SpriteKind.create()
    export const DUck = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vy += -1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.LandingPad, function (sprite, otherSprite) {
    sprite.setVelocity(0, 0)
    sprite.y += -2
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.DUck, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.setVelocity(0, 0)
    sprite.y += -2
    pause(100)
    sprite.y += -3
    pause(100)
    sprite.x += 2
    pause(100)
    sprite.y += 3
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vx += -1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Cloud, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.vx = 0
    sprite.vy = 0
    otherSprite.y += -1
    pause(100)
    otherSprite.y += 1
})
// Control the copter with the + pad
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vx += 1
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vy += 1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.mountain, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.setVelocity(0, 0)
    sprite.x += -2
    pause(100)
    sprite.y += -3
    pause(100)
    sprite.x += 2
    pause(100)
    sprite.y += 3
})
let copter: Sprite = null
game.splash("Cloud Bump", "control pad flying")
scene.setBackgroundColor(9)
copter = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......................ffff......
    .....ffff.........fffffff.......
    .......fffffffffffff............
    ...............f................
    ...............f................
    ..............ef..eee...........
    ....f.........e..eeff11.........
    ..ffffffff....eee2f.1111........
    .....f......eee222f11111........
    .....f...eee222222f11111e.......
    .....feeee22222222ff11f2e.......
    .....ee22222222222fffff2e.......
    .....e222222222222fffff2e.......
    .....ee22222222222fffff2e.......
    ......ee222222e222222ff2e.......
    .......ee22222ee2222222ee.......
    ........eeee2eee222222ee........
    ...........fe...eeeeee..........
    ...........f........f...........
    ......f....f........f.....f.....
    ......ffffffffffffffffffff......
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Helicopter)
copter.setStayInScreen(true)
// Create and place "clouds"  Sprites
let cloud1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud1.x = 20
cloud1.y = 30
let cloud2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud2.x = 50
cloud2.y = 65
let cloud3 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud3.x = 100
cloud3.y = 40
let landing = sprites.create(img`
    58585858585858585858585858585858
    58585858585858585858585858585858
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.LandingPad)
landing.y = 125
let mountain = sprites.create(img`
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ...................1............................
    ...................11...........................
    ..................111...........................
    ..................111...........................
    .................1111...........................
    .................11111..........................
    ................111111..........................
    ................1111111.........................
    ...............11111111.........................
    ...............111111111........................
    ..............1111111111........................
    ..............1111111111........................
    .............111111111111.......................
    ............1111111111111.......................
    ............11111111111111......................
    ............11111111111111......................
    ............11111111111111......................
    ...........1111111111111111.....................
    ...........11111111111111111....................
    ..........111111111111111111....................
    ..........ccccccccccccc1cccc....................
    ..........ccccccccccccccccccc...................
    .........cccccccccccccccccccc...................
    .........ccccccccccccccccccccc..................
    ........cccccccccccccccccccccc..................
    ........ccccccccccccccccccccccc.................
    .......cccccccccccccccccccccccc.................
    .......cccccccccccccccccccccccc.................
    ......cccccccccccccccccccccccccc................
    ......cccccccccccccccccccccccccc................
    .....cccccccccccccccccccccccccccc...............
    .....cccccccccccccccccccccccccccc...............
    ....cccccccccccccccccccccccccccccc..............
    ....cccccccccccccccccccccccccccccc..............
    ....ccccccccccccccccccccccccccccccc.............
    ...cccccccccccccccccccccccccccccccc.............
    ...cccccccccccccccccccccccccccccccc.............
    ..cccccccccccccccccccccccccccccccccc............
    ..cccccccccccccccccccccccccccccccccc............
    ..ccccccccccccccccccccccccccccccccccc...........
    ..ccccccccccccccccccccccccccccccccccc...........
    ..cccccccccccccccccccccccccccccccccccc..........
    ..cccccccccccccccccccccccccccccccccccc..........
    `, SpriteKind.mountain)
mountain.setPosition(116, 105)
let tree = sprites.create(img`
    ........................
    ........................
    ..........bbbb..........
    ........bbddddbb........
    .......bddbbbbddb.......
    ......bdbbddddbbdb......
    .....bdbbdbbbbdbbdb.....
    .....bdbdbddddbdbdb.....
    .....cdbbdbbbbdbbdc.....
    .....cbdbbddddbbdbc.....
    .....efbddbbbbddbce.....
    .....eeffbddddbccee.....
    .....eeeeffcccceee......
    .....ceeeeeeeeeeee......
    .....ceeeeeeeeeeee......
    .....feeeeeeeeeeee......
    .....cceeeeeeeeeee......
    ......feeeeeeeeeee......
    .....6fceeeeeeeeee6.....
    ....6776eeeeeeeee676....
    ...6777666eeee6666776...
    ..67768e67766777667776..
    ...668ee7768867788666...
    ......ee77eeee77ecee....
    ......ee6eeeeee6eef.....
    ......eeeeeeeeeeeef.....
    ......eeeeeeeeeeeef.....
    ......eeeeeeeeeeecf.....
    ......ceeeeeeeeeecf.....
    ......ceeeeeeeeeeff.....
    ......feeeeeeeeeefe.....
    .....6feeeeeeeeeef6.....
    ....6776eeeeeeeee676....
    ...6777666eeee6667776...
    ..6776ee67777777667776..
    ...668ee7768867788666...
    ......ee77eeee67ee......
    ......ee6eeeeee6ce......
    ......eefeeeeeeece......
    ......eeceeeeeeece......
    ......eeceeeeeeefe......
    ......eeceeeeeeefe......
    ......eeeeeeeeeefe......
    ......eeeeeeeeeece......
    .....6eeeeeeeeeece6.....
    ....6776eeeeeeeee676....
    ...6776666eeee6766776...
    ..6776ee77777777667776..
    ...668ce7768867788666...
    ......ce77eeee67ee......
    ......ce6eeeeee6ee......
    ......ceeeeeeeeeee......
    ......fcceeeeeecee......
    ......fccceeececce......
    ......fcceeecceccc......
    ......fccceecceccc......
    ......fccccceceecc......
    .....6fccccccccccf6.....
    ....6776ccccccccc676....
    ...6776676cccc6766776...
    ..6776cc77777777667776..
    ...668cc7768867788666...
    ......cc77cccc67cf......
    ......cc6cccccc6cf......
    `, SpriteKind.Cloud)
tree.setPosition(135, 17)
let mySprite = sprites.create(img`
    . . . . . . . . . . b 2 b . . . 
    . . . . . . . . . b 2 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 2 2 2 2 2 b . . . 
    . . . . b b 2 5 1 f 2 5 4 c . . 
    . . . . b 2 2 1 f f 5 5 4 4 4 b 
    . . . . b 2 2 5 f b 4 4 4 4 b . 
    . . . b 5 2 2 2 2 4 4 4 4 b . . 
    . b b 5 5 5 2 2 2 2 2 2 2 b . . 
    b 5 5 5 b b b 2 2 2 2 2 2 2 b . 
    c 5 5 b 2 2 5 c 2 2 2 2 2 2 b . 
    c b b 5 2 5 c 5 2 2 2 2 2 2 b . 
    c b 2 2 b c 5 5 2 2 2 2 2 2 b . 
    b b c c c 5 5 5 2 2 2 2 2 5 b . 
    . . . . c c 5 5 5 2 2 2 b b . . 
    . . . . . . c c c c c b b . . . 
    `, SpriteKind.DUck)
mySprite.setPosition(26, 102)
